#!/bin/sh
alias ka="killall" \
	mkd="mkdir -pv" \
	cat="bat" \
	rm="rm -v" \
	cp="cp -iv" \
	mv="mv -iv" \
	chafa="chafa -c full" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	calcurse="calcurse -D ~/.config/calcurse" \
	magit="nvim -c MagitOnly" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="$FILE" \
	g="git" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="colorls -h --sd --gs" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	YT="pipe-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner" \
	transde="trans -v -t de" \
	trans="trans -v" \
	ll="ls -l" \
	la="ls -A" \
	lla="ls -lA" \
	nf="clear && neofetch --source '~/Pictures/terry-mouth.png' --backend 'chafa'" \
	7zc="7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on" \
	4chan="python3 ~/4chin.py" \
	recomp="ka picom && picom -b" \
	quickwall="quickwall --setter feh" \
	colormeme="exec 1> >(lolcat >&2)"

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

#ls="ls -hN --color=auto --group-directories-first" \

vf() { fzf | xargs -r -I % $EDITOR % ;}
